spring.application.name=todoapp

spring.threads.virtual.enabled=true

spring.datasource.url=jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE;MODE=PostgreSQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa
spring.jpa.open-in-view=false

management.logging.export.otlp.enabled=false
management.tracing.export.otlp.enabled=false
management.otlp.metrics.export.enabled=false

management.server.port=8081

spring.thymeleaf.cache=false
#spring.thymeleaf.prefix=file:/D:/code/todoapp/src/main/resources/templates/

#ogging.pattern.console=${CONSOLE_LOG_PATTERN:-%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd'T'HH:mm:ss.SSSXXX}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}){} %clr(${PID:-}){magenta} %clr(--- %esb(){APPLICATION_NAME}%esb{APPLICATION_GROUP}[%15.15t] ${LOG_CORRELATION_PATTERN:-}){faint}%clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}
logging.pattern.console=%clr{faint} %clr(%5p){} %clr(${PID:-}){magenta} %clr(%esb{APPLICATION_GROUP}[%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:) %m%n%wEx
logging.level."org.hibernate.SQL"=DEBUG
logging.level."org.hibernate.orm.jdbc.bind"=TRACE
logging.level."org.springframework.security"=INFO